# Generated by Django 3.2.3 on 2021-06-10 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_auto_20210608_1824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='username',
            new_name='handle',
        ),
    ]
