# Generated by Django 3.2.3 on 2021-06-10 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_rename_username_person_handle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='handle',
        ),
        migrations.AddField(
            model_name='person',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
