# Generated by Django 3.2.3 on 2021-06-22 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_alter_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='desirable', to='network.Person'),
        ),
    ]
